//! Day Skies — a weather app built with [Day](https://daybrite.dev). `root()` is the whole UI,
//! shared by every platform. A `selector` over a handful of cities is the adaptive shell: a
//! sidebar + detail split on desktop, a list that pushes the detail on mobile. Each city's weather
//! lives in its own reactive signal, fed by the data layer in `weather.rs`.

use day::prelude::*;
use std::cell::RefCell;

mod icons;
mod settings;
mod ui;
mod weather;

use weather::{Place, Weather};

/// Typed resource + localization constants generated by `day-build` from `resource/` (see build.rs):
/// `res::str::<key>()` for every Fluent message, with the message's params as typed arguments —
/// a missing key or wrong arity is a compile error.
pub mod res {
    include!(concat!(env!("OUT_DIR"), "/day_resources.rs"));
}

day::routes! {
    /// The sidebar sections, typed (https://daybrite.dev/docs/navigation): the five cities plus
    /// Settings. Each key is what deep links and DayScript address, and the `.item(Section::…)`
    /// calls are checked against this.
    pub(crate) enum Section {
        SanFrancisco => "san-francisco",
        NewYork => "new-york",
        London => "london",
        Tokyo => "tokyo",
        Sydney => "sydney",
        Settings => "settings",
    }
}

const SAN_FRANCISCO: Place = Place {
    id: "san-francisco",
    latitude: 37.7749,
    longitude: -122.4194,
};
const NEW_YORK: Place = Place {
    id: "new-york",
    latitude: 40.7128,
    longitude: -74.0060,
};
const LONDON: Place = Place {
    id: "london",
    latitude: 51.5072,
    longitude: -0.1276,
};
const TOKYO: Place = Place {
    id: "tokyo",
    latitude: 35.6762,
    longitude: 139.6503,
};
const SYDNEY: Place = Place {
    id: "sydney",
    latitude: -33.8688,
    longitude: 151.2093,
};
const PLACES: [Place; 5] = [SAN_FRANCISCO, NEW_YORK, LONDON, TOKYO, SYDNEY];

thread_local! {
    /// Per-city weather resources (docs/async.md), memoized by place id so navigating between
    /// cities (which rebuilds the detail pane) reuses the same loaded data.
    static STATES: RefCell<Vec<(&'static str, day::reactive::Resource<Weather>)>> =
        const { RefCell::new(Vec::new()) };
}

/// Get (creating on first call) the weather resource for a place. The resource TRACKS the
/// Save-applied host (`settings::host()`), so applying a new host refetches by itself; mock data
/// resolves synchronously inside the fetcher; the live path awaits the platform fetch through
/// `fetch_future` (docs/http.md) — cancellation and latest-wins ride the Resource.
fn resource_for(place: Place) -> day::reactive::Resource<Weather> {
    STATES.with(|cell| {
        if let Some((_, r)) = cell.borrow().iter().find(|(id, _)| *id == place.id) {
            return *r;
        }
        // Root scope, NOT the calling page's build scope: the resource must outlive the detail
        // pane that first touched it (a page-scoped resource would be disposed on navigation and
        // the memoized handle would go dead — the settings Store's detached-scope rationale).
        let r = day::reactive::Scope::root().enter(|| {
            day::reactive::Resource::new(settings::host, move |host| weather::load(place, host))
        });
        cell.borrow_mut().push((place.id, r));
        r
    })
}

/// Refetch every city (the settings Save action). Save also writes the applied-host signal the
/// resources track, so a CHANGED host refetches twice-deduped into one run (both dependencies
/// dirty in the same drain); an unchanged host still refetches — Save always re-checks.
pub(crate) fn reload_all() {
    STATES.with(|cell| {
        for (_, r) in cell.borrow().iter() {
            r.refetch();
        }
    });
}

fn city_page(place: Place) -> AnyPiece {
    ui::weather_page(place, resource_for(place).signal())
}

pub fn root() -> AnyPiece {
    install_locales(
        "en",
        &[
            ("en", include_str!("../resource/locales/en/app.ftl")),
            ("fr", include_str!("../resource/locales/fr/app.ftl")),
            ("ar", include_str!("../resource/locales/ar/app.ftl")),
            ("zh-CN", include_str!("../resource/locales/zh-CN/app.ftl")),
        ],
    );

    // Create every city's resource in the (permanent) root scope and start loading now.
    for place in PLACES {
        let _ = resource_for(place);
    }

    // Open on the first city so both desktop and mobile show weather immediately.
    let section = Signal::new(Some(Section::SanFrancisco));
    selector(section)
        .style(SelectorStyle::Sidebar)
        .title(res::str::app_title())
        .header(sidebar_header)
        .item(
            Section::SanFrancisco,
            res::str::city_san_francisco(),
            || city_page(SAN_FRANCISCO),
        )
        .item(Section::NewYork, res::str::city_new_york(), || {
            city_page(NEW_YORK)
        })
        .item(Section::London, res::str::city_london(), || {
            city_page(LONDON)
        })
        .item(Section::Tokyo, res::str::city_tokyo(), || city_page(TOKYO))
        .item(Section::Sydney, res::str::city_sydney(), || {
            city_page(SYDNEY)
        })
        .item(
            Section::Settings,
            res::str::settings_title(),
            settings::settings_page,
        )
        .id("nav")
        .any()
}

fn sidebar_header() -> AnyPiece {
    column((
        label(res::str::app_title())
            .font(Font::Headline)
            .id("app-title"),
        label(res::str::app_tagline()).font(Font::Caption),
    ))
    .spacing(2.0)
    .align(HAlign::Leading)
    .padding(12.0)
    .any()
}

// Mobile / embedded entry points — each macro expands to nothing off its own platform.
day::ios_main!("Day Skies", root);
day::android_main!(root);
day::arkui_main!(root);
